name: "🚀 Improvement Request"
description: Suggest an improvement for the SDKs.
labels: ["Type/Improvement"]
body:
  - type: textarea
    id: limitation
    attributes:
      label: Current Limitation
      description: Describe the current limitation.
    validations:
      required: true
  - type: textarea
    id: suggestion
    attributes:
      label: Suggested Improvement
      description: Describe the improvement you suggest.
    validations:
      required: true
  - type: dropdown
    id: area
    attributes:
      label: Please select the package issue is related to
      options:
        - '@asgardeo/browser'
        - '@asgardeo/express'
        - '@asgardeo/javascript'
        - '@asgardeo/nextjs'
        - '@asgardeo/node'
        - '@asgardeo/nuxt'
        - '@asgardeo/react'
        - '@asgardeo/react-router'
        - '@asgardeo/vue'
        - 'samples'
      default: 1
      multiple: true
    validations:
      required: true
  - type: input
    id: version
    attributes:
      label: Version
      description: Enter package version or commit hash.
    validations:
      required: true
  - type: checkboxes
    id: reporter-checklist
    attributes:
      label: Reporter Checklist
      description: Please review and confirm the following items before opening the improvement request.
      options:
        - label: "I have searched the existing issues and this is not a duplicate."
          required: true
        - label: "I have provided all the necessary information."
          required: true
        - label: "I have verified the improvement is not available in the latest version of the package."
          required: true
