/**
 * Copyright (c) 2024, WSO2 LLC. (https://www.wso2.com). All Rights Reserved.
 *
 * WSO2 LLC. licenses this file to you under the Apache License,
 * Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 * KIND, either express or implied. See the License for the
 * specific language governing permissions and limitations
 * under the License.
 */

import {TOTP} from './model';

export const totp: TOTP = {
  continue: 'Continue',
  'enter.verification.code.got.by.device': 'Enter the verification code generated by your authenticator app.',
  'totp.enroll.message1': "Haven't setup your TOTP authenticator yet?",
  'totp.enroll.message2': 'Contact Support',
  'totp.heading': 'Verify Your Identity',
};
